#!/usr/bin/env python3
"""Configuration file for the Sphinx documentation builder."""

import datetime
import os
import re
import sys
from pathlib import Path

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

ON_READTHEDOCS = os.environ.get("READTHEDOCS") == "True"
if not ON_READTHEDOCS:
    sys.path.insert(0, os.path.abspath("../../src"))

import hyperactive  # noqa: E402  # must be after sys.path modification

# -- Extract metadata from pyproject.toml ------------------------------------
# This allows documentation to stay in sync with pyproject.toml automatically

def extract_pyproject_metadata():
    """Extract metadata from pyproject.toml for use in documentation."""
    pyproject_path = Path(__file__).parent.parent.parent / "pyproject.toml"

    metadata = {
        "python_versions": [],
        "min_python": "3.10",
        "dependencies": [],
        "version": hyperactive.__version__,
    }

    if pyproject_path.exists():
        content = pyproject_path.read_text()

        # Extract Python versions from classifiers
        # Pattern: "Programming Language :: Python :: 3.XX"
        py_version_pattern = r'"Programming Language :: Python :: (3\.\d+)"'
        versions = re.findall(py_version_pattern, content)
        if versions:
            metadata["python_versions"] = sorted(set(versions))

        # Extract requires-python
        requires_python_match = re.search(r'requires-python\s*=\s*"([^"]+)"', content)
        if requires_python_match:
            req = requires_python_match.group(1)
            # Extract minimum version from ">=3.10" or similar
            min_match = re.search(r">=\s*([\d.]+)", req)
            if min_match:
                metadata["min_python"] = min_match.group(1)

        # Extract core dependencies
        deps_match = re.search(
            r"dependencies\s*=\s*\[(.*?)\]", content, re.DOTALL
        )
        if deps_match:
            deps_text = deps_match.group(1)
            # Extract package names (first word before any version specifier)
            dep_names = re.findall(r'"([a-zA-Z][a-zA-Z0-9_-]*)', deps_text)
            metadata["dependencies"] = dep_names

    return metadata


# Extract metadata once at configuration time
PYPROJECT_METADATA = extract_pyproject_metadata()

# Build Python version range string from metadata
_py_versions = PYPROJECT_METADATA["python_versions"]
if _py_versions:
    _py_version_range = f"{_py_versions[0]} - {_py_versions[-1]}"
else:
    _py_version_range = "3.10+"

# -- Project information -----------------------------------------------------
current_year = datetime.datetime.now().year
project = "hyperactive"
project_copyright = f"2019 - {current_year} (MIT License)"
author = "Simon Blanke"

# The full version, including alpha/beta/rc tags
CURRENT_VERSION = f"v{hyperactive.__version__}"

# If on readthedocs, and we're building the latest version, update tag to generate
# correct links in notebooks
if ON_READTHEDOCS:
    READTHEDOCS_VERSION = os.environ.get("READTHEDOCS_VERSION")
    if READTHEDOCS_VERSION == "latest":
        CURRENT_VERSION = "main"

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.autosectionlabel",
    "numpydoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.linkcode",  # link to GitHub source code via linkcode_resolve()
    "myst_parser",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_issues",
    "sphinx.ext.doctest",
]

# Recommended by sphinx_design when using the MyST Parser
myst_enable_extensions = ["colon_fence"]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
source_suffix = {
    ".rst": "restructuredtext",
    ".md": "markdown",
}

# The main toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = [
    "_build",
    ".ipynb_checkpoints",
    "Thumbs.db",
    ".DS_Store",
]

add_module_names = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# see http://stackoverflow.com/q/12206334/562769
numpydoc_show_class_members = True
# this is needed for some reason...
# see https://github.com/numpy/numpydoc/issues/69
numpydoc_class_members_toctree = False

# https://numpydoc.readthedocs.io/en/latest/validation.html#built-in-validation-checks
# Let's turn off the check for building but keep it in pre-commit hooks
numpydoc_validation_checks = set()

# generate autosummary even if no references
autosummary_generate = True

# Members and inherited-members default to showing methods and attributes from a
# class or those inherited.
# Member-order orders the documentation in the order of how the members are defined in
# the source code.
autodoc_default_options = {
    "members": True,
    "inherited-members": True,
    "member-order": "bysource",
}

# If true, '()' will be appended to :func: etc. cross-reference text.
add_function_parentheses = False

# Suppress warnings
suppress_warnings = [
    "myst.mathjax",
    "docutils",
    "toc.not_included",
    "autodoc.import_object",
    "autosectionlabel",
    "ref",
]

show_warning_types = True

# Link to GitHub repo for github_issues extension
issues_github_path = "SimonBlanke/Hyperactive"


def linkcode_resolve(domain, info):
    """Return URL to source code corresponding.

    Parameters
    ----------
    domain : str
    info : dict

    Returns
    -------
    url : str
    """

    def find_source():
        # try to find the file and line number, based on code from numpy:
        # https://github.com/numpy/numpy/blob/main/doc/source/conf.py#L286
        obj = sys.modules[info["module"]]
        for part in info["fullname"].split("."):
            obj = getattr(obj, part)
        import inspect
        import os

        fn = inspect.getsourcefile(obj)
        fn = os.path.relpath(fn, start=os.path.dirname(hyperactive.__file__))
        source, lineno = inspect.getsourcelines(obj)
        return fn, lineno, lineno + len(source) - 1

    if domain != "py" or not info["module"]:
        return None
    try:
        filename = "src/hyperactive/%s#L%d-L%d" % find_source()
    except Exception:
        filename = info["module"].replace(".", "/") + ".py"
    return f"https://github.com/SimonBlanke/Hyperactive/blob/{CURRENT_VERSION}/{filename}"


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = "pydata_sphinx_theme"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.

html_theme_options = {
    "icon_links": [
        {
            "name": "GitHub",
            "url": "https://github.com/SimonBlanke/Hyperactive",
            "icon": "fab fa-github",
        },
        {
            "name": "Star on GitHub",
            "url": "https://github.com/SimonBlanke/Hyperactive/stargazers",
            "icon": "fa-regular fa-star",
        },
    ],
    "show_prev_next": False,
    "use_edit_page_button": False,
    "navbar_start": ["navbar-logo"],
    "navbar_center": ["navbar-nav"],
    "navbar_end": ["theme-switcher", "navbar-icon-links"],
    "show_toc_level": 2,
    "secondary_sidebar_items": ["page-toc", "sourcelink"],
}

html_title = "Hyperactive"
html_context = {
    "github_user": "SimonBlanke",
    "github_repo": "Hyperactive",
    "github_version": "master",
    "doc_path": "auto-doc/source/",
    "python_version_range": _py_version_range,
}

html_sidebars = {
    "**": ["sidebar-nav-bs.html"],
    "index": [],
    "get_started": [],
    "installation": [],
    "search": [],
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]
html_css_files = ["css/custom.css"]

html_show_sourcelink = False

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = "hyperactivedoc"

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "hyperactive.tex",
        "Hyperactive Documentation",
        "Simon Blanke",
        "manual",
    ),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "hyperactive", "Hyperactive Documentation", [author], 1)]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "hyperactive",
        "Hyperactive Documentation",
        author,
        "hyperactive",
        "An optimization and data collection toolbox for convenient and fast prototyping.",
        "Miscellaneous",
    ),
]


def setup(app):
    """Set up sphinx builder.

    Parameters
    ----------
    app : Sphinx application object
    """

    def adds(pth):
        print("Adding stylesheet: %s" % pth)  # noqa: T201, T001
        app.add_css_file(pth)

    adds("fields.css")  # for parameters, etc.


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": (f"https://docs.python.org/{sys.version_info.major}", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "scipy": ("https://docs.scipy.org/doc/scipy/", None),
    "matplotlib": ("https://matplotlib.org/stable/", None),
    "pandas": ("https://pandas.pydata.org/pandas-docs/stable/", None),
    "joblib": ("https://joblib.readthedocs.io/en/stable/", None),
    "scikit-learn": ("https://scikit-learn.org/stable/", None),
}

# -- Options for todo extension ----------------------------------------------
todo_include_todos = False

copybutton_prompt_text = r">>> |\.\.\. |\$ "
copybutton_prompt_is_regexp = True
copybutton_line_continuation_character = "\\"

# -- RST Epilog: Make metadata available as substitutions in RST files -------
# These can be used as |variable_name| in RST files

# Build additional Python versions formatting for RST
if _py_versions:
    _py_versions_inline = ", ".join(_py_versions)
else:
    _py_versions_inline = "3.10+"

rst_epilog = f"""
.. |version| replace:: {PYPROJECT_METADATA["version"]}
.. |min_python| replace:: {PYPROJECT_METADATA["min_python"]}
.. |python_versions_list| replace:: {_py_versions_inline}
.. |python_version_range| replace:: {_py_version_range}
.. |current_year| replace:: {current_year}
"""
